### PR TITLE
fix: stop music playing when modal is closed

### LINKED ISSUE #16: CloudUpload: Stop playing music when modal is closed
**Describe the bug**
After closing the modal, music playing is not stopped.

**Expected behavior**
Stop

### PR DESCRIPTION
**Pull request by so1ve**
close #16

### CODE REVIEW

**Comment by y-young** [comment]
This is a little bit strange, maybe consider using a ref and call `stop()`, like here: https://github.com/y-young/f1music/blob/6aff87346fbdd893472e0c5257c9f41cbd7e1bc7/react/src/components/VoteList.js#L56

**Comment by so1ve** [comment]
> This is a little bit strange, maybe consider using a ref and call `stop()`, like here:
> 
> https://github.com/y-young/f1music/blob/6aff87346fbdd893472e0c5257c9f41cbd7e1bc7/react/src/components/VoteList.js#L56

(っ °Д °;)っ You are right

**Comment by so1ve** [comment]
忘了可以用ref，，，要不然您直接推一个commit，或者我明天改一下pr？

**Comment by y-young** [comment]
等你改吧，不着急
我还在重构（

**Comment by so1ve** [comment]
@y-young ok力（

**Review by y-young — APPROVED** [review]

**Pull request merged**
